platform :ios, '9.0'
use_frameworks!

target 'PowerTools_Example' do
  pod 'PowerTools', :path => '../'

  target 'PowerTools_Tests' do
    inherit! :search_paths
    pod 'PowerToolsTester', :path => '../'
    
  end
end
